#pragma once

#define MASTER_LEFT

#ifdef CONVERTER_ENABLED
    #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
    #define RGB_MATRIX_SLEEP
    #define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
    #define ENABLE_RGB_MATRIX_SOLID_COLOR
#endif
